# Generated by Django 5.2.9 on 2025-12-17 12:10

import django.db.models.deletion
import materiales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('material_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('link', 'Enlace'), ('document', 'Documento'), ('presentation', 'Presentación'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de material')),
                ('file', models.FileField(blank=True, null=True, upload_to=materiales.models.material_upload_path, verbose_name='Archivo')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='cursos.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
